### PR TITLE
[Paladin] Update Holy

### PR DESCRIPTION
**Pull request by doadin**

### CODE REVIEW

**Comment by pwilkowski** [comment]
If you are updating to new version, please:

1. Update the actual TOC with new version (similar to wow patch naming ex `9.1.0`) as well as build version.
2. Please add semicolons to code even if lua doesnt require it (for code integrity)

**Comment by doadin** [comment]
@pwilkowski  Is that what you wanted?

**Comment by pwilkowski** [comment]
perfect, gonna make release now

**Comment by pwilkowski** [comment]
@doadin do you perhaps also play Retri? I have some experimental version that could be worth checking out (replace entire Retribution.lua), if you can we can also merge that one

https://pastebin.com/fWaA1WRw

**Comment by doadin** [comment]
@pwilkowski I play all 12 classes but not every spec, and unfortunately I don't really play ret, I could take a look, currently though I am working on all the healing specs for all the healing classes since it seems nobody has done those.

**Pull request merged**
